### ISSUE TITLE
Get the Error about Pip subprocess error: ERROR: Could not find a version that satisfies the requirement cpython==0.0.6 (from versions: none) ERROR: No matching distribution found for cpython==0.0.6

### ISSUE THREAD

**Issue by Tianyulied** [YNCris/SBeA_release#1]
Hello,
i have see your paper and it is very useful software.
But when i install the software by using "conda env create -f environment.yml --name SBeA" in anaconda, I get the error about
![image](https://github.com/YNCris/SBeA_release/assets/119161703/17834740-3c0e-4dc3-b692-b88bb0e963d3)
 it say :
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement cpython==0.0.6 (from versions: none)
ERROR: No matching distribution found for cpython==0.0.6
I dont know how to solve about it.
thanks and looking for you reply

**Comment by YNCris** [comment]
Hello,

This bug can be fixed by commenting 'cpython==0.0.6' in the environment.yml. The environment.yml is updated. You can download it directly.  

Thank you for trying our Social Behavior Atlas!
