### ISSUE TITLE
Inquiry about the calibration file.

### ISSUE THREAD

**Issue by BBrianZhang** [YNCris/SBeA_release#2]
Hello, I have encountered some issues while using your code. The 3D reconstruction requires a calibration file. Could you please specify the format requirements for the calibration file? Could you provide a reference, or could you provide a basic completed project file for reference? Thank you for your open-source project.
![image](https://github.com/YNCris/SBeA_release/assets/102034510/a7a2c221-cd11-4b2f-9ef0-da605ffc486c)

**Comment by YNCris** [comment]
Hello! Thank you for trying our Social Behavior Atlas. The format of the calibration file is based on the 3D-AI behavior atlas system. You can find some details on https://www.behavioratlas.cn/. It is a society of behavior analysis. I don't know if your institute has this device. It would be easier to check the calibration file on the 3D-AI system. The link to the data for reproduction has been provided at the https://github.com/YNCris/SBeA_release/blob/main/README_SBeA_tracker.md. You can find the data link at the end of each section. All the data are provided at https://figshare.com/articles/dataset/SBeA_upload_data/22314994. It contains the calibration file and some of the completed projects. If you still have some questions, please feel free to ask here. I will answer to you as soon as possible.
