### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by dora0311** [YNCris/SBeA_release#7]
Hi!
I am trying to use your very useful software, SBeA. I have successfully loaded the provided case data, fig2_data, and output the processed data. However, When I try to click the "train model" button, a "RuntimeError: Error(s) in loading state_dict for ResNetBackbone" occurs.The error seems to be related to loading a pretrained ResNet backbone, where the shape of the weights in the current model does not match the checkpoint.
```
F:\anaconda\envs\sbaw\python.exe F:/Laboratory/SBeA_release-main/SBeA_tracker/SBeA-Windows-main/gui/main.py
Loading DLC 2.2.3...
transfer labelme dataset to coco dataset...
transfer finished!
train yolact...
Scaling parameters by 2.00 to account for a batch size of 16.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Initializing weights...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\anaconda\envs\sbaw\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "F:\anaconda\envs\sbaw\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "gui\load_label_train.py", line 149, in load_label_train.LoadLabelTrain.data_gen_and_train
  File "SocialBehaviorAtlas\train_seg_models.py", line 37, in train_seg_models.train_data_generation
  File "SocialBehaviorAtlas\train_utils\train_yolact.py", line 12, in train_yolact.train_yolact
  File "x\sbea_train.py", line 585, in sbea_train.sbea_train
  File "x\sbea_train.py", line 285, in sbea_train.sbea_train.train
  File "F:\Laboratory\SBeA_release-main\SBeA_tracker\SBeA-Windows-main\SocialBehaviorAtlas\train_utils\yolact\yolact.py", line 495, in init_weights
    self.backbone.init_backbone(backbone_path)
  File "F:\Laboratory\SBeA_release-main\SBeA_tracker\SBeA-Windows-main\SocialBehaviorAtlas\train_utils\yolact\backbone.py", line 193, in init_backbone
    self.load_state_dict(state_dict, strict=False)
  File "F:\anaconda\envs\sbaw\lib\site-packages\torch\nn\modules\module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNetBackbone:
	size mismatch for layers.0.0.downsample.1.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for layers.1.0.downsample.1.weight: copying a param with shape torch.Size([512, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for layers.2.0.downsample.1.weight: copying a param with shape torch.Size([1024, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for layers.3.0.downsample.1.weight: copying a param with shape torch.Size([2048, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([2048]).
```
I tried setting the strict parameter to `False` in `load_state_dict`, but it doesn't work.I dont know how to solve about it.

Thanks in advance for your help!

**Comment by YNCris** [comment]
Thanks for your use of sbea! I can provide you with two ways to solve this problem. I recommend you try it one by one. 

1. Because the training of yolact needs a backbone downloaded online, you need to first check if there exists the right pretrained model in the folder .\models\yolact. You can download the pretrained backbone at "https://github.com/dbolya/yolact".

2. If the pretrained model is right and you still cannot run it (sometimes it happens in another of my computer and I also have no idea about how to solve this problem...), you can separately use yolact or other models to train it directly using the dataset. All the related datasets are in .\datasets folder. What you need is only to follow the format of each dataset. 

Please feel free to contact me again if you have any further questions!

**Comment by dora0311** [comment]
Thank you so much for your quick reply! 
I tried the first option you came up with and it still doesn't work. I'm going to try other software and try the second option if I have the chance, or try running Sbea on a different PC.

**Comment by YNCris** [comment]
Sorry about the not working solutions. Sbea involves 4 different models so it always has some problems in debug. So I designed it into separate steps with accessible data format. Anyway, thanks a lot for trying it!
